version: '3'

services:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017

  activemq:
    container_name: activemq
    image: rmohr/activemq
    ports:
      - 61616:61616
      - 8161:8161

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  mysql:
    container_name: mysql
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 172.*.*.*
      MYSQL_DATABASE: demo
      MYSQL_USER: skeyal
      MYSQL_PASSWORD: skeyal
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: