version: '2'

networks:
  kafka-net:
    driver: bridge

services:

  mysql-db-server:
    image: mysql/mysql-server
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '4444:3306'
    networks:
      - kafka-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 172.*.*.*
      MYSQL_DATABASE: demo
      MYSQL_USER: skeyal
      MYSQL_PASSWORD: skeyal

  app-server:
    build: .
    container_name: demo
    ports:
      - '7070:7070'
    networks:
      - kafka-net
    environment:
      - MYSQL_HOST=mysql-db-server
      - MYSQL_USERNAME=skeyal
      - MYSQL_PASSWORD=skeyal

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
#  zookeeper-server:
#    image: 'bitnami/zookeeper:latest'
#    container_name: zookeeper
#    networks:
#      - kafka-net
#    ports:
#      - '2181:2181'
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#
#  kafka-server1:
#    image: 'bitnami/kafka:latest'
#    container_name: kafka1
#    networks:
#      - kafka-net
#    ports:
#      - '9092:9092'
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper-server
#
#  kafka-server2:
#    image: 'bitnami/kafka:latest'
#    container_name: kafka2
#    networks:
#      - kafka-net
#    ports:
#      - '9092'
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
#      - KAFKA_ADVERTISED_HOST_NAME:kafka
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper-server