version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '4444:3306'
    networks:
      - demo-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 172.*.*.*
      MYSQL_DATABASE: demo
      MYSQL_USER: skeyal
      MYSQL_PASSWORD: skeyal